# Generated by Django 6.1 on 2026-08-30 09:33

from django.db import migrations


def seed_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    services = [
        {
            'title': 'General practice',
            'description': 'Everyday health concerns, preventive care and ongoing support.',
            'price': 300,
        },
        {
            'title': 'Cardiology',
            'description': 'Heart health diagnosis and long-term management.',
            'price': 500,
        },
        {
            'title': 'Pediatrics',
            'description': 'Gentle, specialised care for children of all ages.',
            'price': 350,
        },
        {
            'title': 'Laboratory',
            'description': 'Fast, reliable results with on-site testing available.',
            'price': 250,
        },
    ]
    for service in services:
        Service.objects.create(**service)


def remove_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    Service.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_services, remove_services),
    ]