# Generated by Django 6.1 on 2026-08-30 09:48

from django.db import migrations

SERVICE_IMAGES = {
    'General practice': 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=900',
    'Cardiology': 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?q=80&w=900',
    'Pediatrics': 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?q=80&w=900',
    'Laboratory': 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?q=80&w=900',
}


def add_service_images(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    for service in Service.objects.all():
        if service.title in SERVICE_IMAGES:
            service.image = SERVICE_IMAGES[service.title]
            service.save()


def remove_service_images(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    Service.objects.update(image=None)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_services'),
    ]

    operations = [
        migrations.RunPython(add_service_images, remove_service_images),
    ]