# Generated by Django 6.1 on 2026-08-30 10:01

from django.db import migrations

MORE_SERVICES = [
    ('Dermatology', 'Skin, hair and nail care with modern diagnostic tools.', 400,
     'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=900'),
    ('Dentistry', 'Preventive dental care, cleanings and restorative treatments.', 350,
     'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=900'),
    ('Ophthalmology', 'Eye exams, vision screening and prescription fitting.', 300,
     'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?q=80&w=900'),
    ('Orthopedics', 'Joint, bone and muscle care for pain relief and recovery.', 550,
     'https://images.unsplash.com/photo-1551601651-2a8555f1a136?q=80&w=900'),
    ('Physiotherapy', 'Rehabilitation sessions to restore mobility and strength.', 400,
     'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=900'),
    ('Nutrition & Dietetics', 'Personalised meal plans and lifestyle guidance.', 250,
     'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=900'),
    ('Ultrasound & Imaging', 'On-site ultrasound and diagnostic imaging scans.', 450,
     'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?q=80&w=900'),
    ('Vaccination', 'Childhood immunisations and seasonal vaccination programs.', 150,
     'https://images.unsplash.com/photo-1584982751601-97dcc096659c?q=80&w=900'),
    ('Psychology', 'Confidential counselling and mental health support.', 500,
     'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=900'),
    ('ENT', 'Ear, nose and throat examinations and treatments.', 400,
     'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?q=80&w=900'),
    ('Dermatosurgery', 'Minor surgical procedures for skin conditions.', 350,
     'https://images.unsplash.com/photo-1580281657527-47f249e8f4df?q=80&w=900'),
    ('Gynecology', 'Women\u2019s health check-ups and prenatal care.', 500,
     'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?q=80&w=900'),
    ('Urology', 'Diagnosis and management of urinary tract conditions.', 600,
     'https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=900'),
    ('Emergency Medicine', 'Immediate care for urgent medical needs.', 800,
     'https://images.unsplash.com/photo-1538108149393-fbbd81895907?q=80&w=900'),
    ('Radiology', 'X-ray and advanced imaging diagnostics.', 500,
     'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=900'),
    ('Health Checkup Package', 'A complete annual health screening for the whole body.', 900,
     'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=900'),
]


def add_more_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    for title, description, price, image in MORE_SERVICES:
        Service.objects.create(
            title=title,
            description=description,
            price=price,
            image=image,
        )


def remove_more_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    titles = [item[0] for item in MORE_SERVICES]
    Service.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_service_images'),
    ]

    operations = [
        migrations.RunPython(add_more_services, remove_more_services),
    ]