# Generated by Django 6.1

from django.db import migrations


def clear_url_images(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    # Existing rows stored full HTTP(S) URLs as plain strings. The image field
    # is now treated as an uploaded file, so these old URL strings cannot be
    # serialised as ImageField values. Clear them so services can be updated
    # with real uploaded images.
    Service.objects.exclude(image='').exclude(image__isnull=True).update(image=None)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_more_services'),
    ]

    operations = [
        migrations.RunPython(clear_url_images, migrations.RunPython.noop),
    ]
